rootProject.name = "zMenu"

include("API")
include("Hooks:ItemsAdder")
include("Hooks:HeadDataBase")
include("Hooks:CraftEngine")
include("Hooks:Eco")
include("Hooks:Hmccosmetics")
include("Hooks:MagicCosmetics")
include("Hooks:Nexo")
include("Hooks:Nova")
include("Hooks:Oraxen")
include("Hooks:SlimeFun")
include("Hooks:ZHead")
include("Hooks:ZItems")
include("Hooks:PacketEvents")
include("Hooks:LuckPerms")
include("Hooks:Shopkeepers")
