name: zMenu
authors: [ Maxlego08 ]
main: fr.maxlego08.menu.ZMenuPlugin
description: Inventory management plugin
website: https://groupez.dev/resources/zmenu.253
version: ${version}
api-version: '1.19'
contributors: [ mani1232, lijinhong11, Adreez, EnzoShoes, Noltox, saildrag, alwyn974, 1robie, Funasitien ]
bootstrapper: fr.maxlego08.menu.ZMenuBootstrapper
loader: fr.maxlego08.menu.ZMenuPluginLoader
folia-supported: true
dependencies:
  server:
    CraftEngine:
      load: BEFORE
      required: false
      join-classpath: true

    Denizen:
      load: BEFORE
      required: false
      join-classpath: true

    Shopkeepers:
      load: BEFORE
      required: false
      join-classpath: true

    zItems:
      load: BEFORE
      required: false
      join-classpath: true

    Oraxen:
      load: BEFORE
      required: false
      join-classpath: true

    eco:
      load: BEFORE
      required: false
      join-classpath: true

    Nexo:
      load: BEFORE
      required: false
      join-classpath: true

    NextGens:
      required: false
      join-classpath: true

    Nova:
      load: BEFORE
      required: false
      join-classpath: true

    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true

    HeadDatabase:
      load: BEFORE
      required: false
      join-classpath: true

    ItemsAdder:
      load: BEFORE
      required: false
      join-classpath: true

    Slimefun:
      load: BEFORE
      required: false
      join-classpath: true

    # JobsReborn
    Jobs:
      load: BEFORE
      required: false
      join-classpath: true

    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true

    zHead:
      load: BEFORE
      required: false
      join-classpath: true

    MagicCosmetics:
      load: BEFORE
      required: false
      join-classpath: true

    packetevents:
      load: BEFORE
      required: false
      join-classpath: true

    HMCCosmetics:
      load: BEFORE
      required: false
      join-classpath: true

    SCore:
      load: BEFORE
      required: false
      join-classpath: true

    ExecutableItems:
      load: BEFORE
      required: false
      join-classpath: true

    ExecutableBlocks:
      load: BEFORE
      required: false
      join-classpath: true

    MythicMobs:
      load: BEFORE
      required: false
      join-classpath: true

    MMOItems:
      load: BEFORE
      required: false
      join-classpath: true

    BreweryX:
      load: BEFORE
      required: false
      join-classpath: true

    floodgate:
      load: BEFORE
      required: false
      join-classpath: true

    Geyser-Spigot:
      load: BEFORE
      required: false
      join-classpath: true

    # -- Economy plugins
    Vault:
      required: false
      join-classpath: true

    BeastTokens:
      required: false
      join-classpath: true

    PlayerPoints:
      required: false
      join-classpath: true

    ElementalTokens:
      required: false
      join-classpath: true

    ElementalGems:
      required: false
      join-classpath: true

    zEssentials:
      required: false
      join-classpath: true

    EcoBits:
      required: false
      join-classpath: true

    CoinsEngine:
      required: false
      join-classpath: true

    ExcellentEconomy:
      required: false
      join-classpath: true

    VotingPlugin:
      required: false
      join-classpath: true

    RedisEconomy:
      required: false
      join-classpath: true

    RoyaleEconomy:
      required: false
      join-classpath: true