name: zMenu
authors: [ Maxlego08 ]
main: fr.maxlego08.menu.MenuPlugin
description: Inventory management plugin
website: https://groupez.dev/resources/zmenu.253
version: ${project.version}
api-version: 1.13
contributors: [ mani1232, lijinhong11, Adreez, EnzoShoes ]
softdepend:
- HeadDatabase
- PlaceholderAPI
- zTranslator
- ItemsAdder
- Slimefun
- eco
- Jobs
folia-supported: true