name: zMenu
authors: [ Maxlego08 ]
main: fr.maxlego08.menu.ZMenuPlugin
description: Inventory management plugin
website: https://groupez.dev/resources/zmenu.253
version: ${version}
api-version: 1.19
contributors: [ mani1232, lijinhong11, Adreez, EnzoShoes, Noltox, saildrag, alwyn974, 1robie ]
softdepend:
  - HeadDatabase
  - PlaceholderAPI
  - ItemsAdder
  - Slimefun
  - Jobs
  - LuckPerms
  - zHead
  - MagicCosmetics
  - packetevents
  - HMCCosmetics
  - SCore
  - ExecutableItems
  - ExecutableBlocks
  - MythicMobs
  - BreweryX
  - floodgate
  - Geyser-Spigot
folia-supported: true
loadbefore:
  - SuperiorSkyblock2
libraries:
  - org.mariadb.jdbc:mariadb-java-client:3.5.6
