package fr.maxlego08.menu.common.enums;

import java.util.Locale;

public enum Permission {
	
	ZMENU_RELOAD,
    ZMENU_RELOAD_COMMAND,
    ZMENU_RELOAD_INVENTORY,
    ZMENU_RELOAD_CONFIG,
	ZMENU_OPEN,
    ZMENU_OPEN_MAIN_MENU,
	ZMENU_SAVE,
	ZMENU_USE,
	ZMENU_PLAYERS,
    ZMENU_PLAYERS_SET,
    ZMENU_PLAYERS_ADD,
    ZMENU_PLAYERS_CLEAR_ALL,
    ZMENU_PLAYERS_CLEAR_PLAYER,
    ZMENU_PLAYERS_CONVERT,
    ZMENU_PLAYERS_GET,
    ZMENU_PLAYERS_KEYS,
    ZMENU_PLAYERS_REMOVE,
    ZMENU_PLAYERS_REMOVE_ALL,
    ZMENU_PLAYERS_SUBTRACT,
	ZMENU_CONVERT,
	ZMENU_LIST,
	ZMENU_TEST_DUPE,
	ZMENU_CREATE,
    ZMENU_DOWNLOAD,
    ZMENU_LOGIN,
    ZMENU_CONNECT,
    ZMENU_DISCONNECT,
    ZMENU_UNLINK,
    ZMENU_MARKETPLACE,
    ZMENU_INVENTORIES,
    ZMENU_DESCRIPTION,
    ZMENU_DIALOG,
    ZMENU_OPEN_DIALOG,
    ZMENU_OPEN_DIALOG_CONFIG,
    ZMENU_RELOAD_DIALOG,
    ZMENU_OPEN_BEDROCK,
    ZMENU_RELOAD_BEDROCK,
    ZMENU_DUMPLOG,
    ZMENU_CONTRIBUTORS,
    ZMENU_GIVE_ITEM,
    ZMENU_GIVE_OPEN_ITEM,
    ZMENU_EDITOR,
    ZMENU_VERSION,

    ZMENU_BEDROCK,
    ZMENU_ADDONS,
    ZMENU_DOCUMENTATION, ZMENU_WEBSITE;

	private final String permission;

	Permission() {
		this.permission = this.name().toLowerCase(Locale.ROOT).replace("_", ".");
	}

	public String getPermission() {
		return this.permission;
	}

}
